### ISSUE TITLE
[FEAT] 文本支持前后移动

### ISSUE THREAD

**Issue by blank038** [EaseCation/cube-3d-text#2]
您好，如果文本能够支持前后移动功能，我相信可以实现许多有趣效果。请问这个功能是否已经在开发计划中？

**Comment by boybook** [comment]
嗯已经做好了哦，在此更新中添加了该功能～
https://github.com/EaseCation/cube-3d-text/commit/d76f93f3608d371526b374c18e18de2911a90800
