### ISSUE TITLE
[ENHANCE] 适配优化手机端的Web使用体验

### ISSUE THREAD

**Issue by ColorCard** [EaseCation/cube-3d-text#3]
如图，元素摆放和缩放对于手机端来说不是太合理，希望能够适配和优化。
![image](https://github.com/user-attachments/assets/ba29bdad-0149-4f61-8e5b-a21215f1a5ac)

使用浏览器：Safari

**Comment by boybook** [comment]
后面找时间会做一下哦，不过得花时间设计手机端交互～

**Comment by boybook** [comment]
已完成了手机端适配！还有什么体验问题可以继续提出哦～
https://github.com/EaseCation/cube-3d-text/commit/037e88861ea5e5150d1898389a94dbdf9fc00e74
