### ISSUE TITLE
[BUG] HTML <lang> 属性错误，应为 zh-CN

### ISSUE THREAD

**Issue by ColorCard** [EaseCation/cube-3d-text#5]
### 问题 
在检查项目的 HTML 文件时，发现 `<html>` 标签中的 `lang` 属性值设置不正确。目前的值可能导致用户浏览器的语言环境错误识别，导致谷歌翻译异常启动，影响用户体验。

### 影响 
- 会导致浏览器谷歌翻译异常启动。
- 搜索引擎可能会错误判断页面的语言，降低页面的 SEO 排名。
- 对用户的语义提示和辅助功能的支持可能受限。

### 可复现步骤
1. 打开网站。
2. 查看 HTML 源代码的 `<html>` 标签。
3. 发现 `lang` 属性错误地设置为 `en`。

**Comment by boybook** [comment]
本项目原生支持多语言，因此需要动态映射，已经在 https://github.com/EaseCation/cube-3d-text/commit/ecd2dd69b3af2dfab49cc1ae4c3d979ef405abde 中修复啦！
