### ISSUE TITLE
[BUG] 字体描边存在异常

### ISSUE THREAD

**Issue by ColorCard** [EaseCation/cube-3d-text#8]
### 描述问题
例如：我生成一个Minecraft Demo的文本图片，其中"Minecraft"中的字母描边存在异常，描边扩大之后这种影响会更加突出。

### 异常位置
【如图所示】

![screenshot (1)](https://github.com/user-attachments/assets/b138c04b-0452-4255-9d55-eede28ff443c)

<img width="1030" alt="image" src="https://github.com/user-attachments/assets/0a1cb99d-aa8b-4986-8eb5-8737c62c071f" />

【预期显示对比】

![Global-Header_MCCB-Logo_300x51](https://github.com/user-attachments/assets/7a0fd28e-c4ed-4799-ab95-f2d68845978f)

**Comment by boybook** [comment]
恭喜🎉 目前已在https://github.com/EaseCation/cube-3d-text/commit/f9b0931f5962a64fafe134b642dbcde443f965a7修复！
